version: "3"

services:

#  k8s-logging:
#    build: .
#    ports:
#      - 5005:5005
#    volumes:
#      - "~/.sbt:/root/.sbt"
#      - "~/.ivy2:/root/.ivy2"
#      - ".:/opt/k8s-logging"
#      - "/opt/k8s-logging/target"
#      - "/opt/k8s-logging/project/target"
#      - "/root/.sbt/1.0/plugins"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
